AWSTemplateFormatVersion: "2010-09-09"
Description: "ECS service with Service Connect and ECR version in DNS"

Parameters:
  ClusterName:
    Type: String
    Default: "MyEcsCluster"
  
  ServiceName:
    Type: String
    Default: "my-service"

  ServiceVersion:
    Type: String
    Description: "The version of the service, typically the ECR image tag."

  DesiredCount:
    Type: Number
    Default: 1
  
  Subnet1:
    Type: String
  Subnet2:
    Type: String
  SecurityGroup:
    Type: String

Resources:

  # ECS Task Definition
  TaskDefinition:
    Type: "AWS::ECS::TaskDefinition"
    Properties:
      Family: !Sub "${ServiceName}-task-${ServiceVersion}"
      NetworkMode: "awsvpc"
      RequiresCompatibilities: 
        - FARGATE
      Cpu: "256"
      Memory: "512"
      ContainerDefinitions:
        - Name: "app-container"
          Image: !Sub "123456789012.dkr.ecr.us-east-1.amazonaws.com/${ServiceName}:${ServiceVersion}"
          PortMappings:
            - ContainerPort: 80
              Protocol: tcp

  # ECS Service with Service Connect
  ECSService:
    Type: "AWS::ECS::Service"
    Properties:
      Cluster: !Ref ClusterName
      ServiceName: !Sub "${ServiceName}-${ServiceVersion}"
      TaskDefinition: !Ref TaskDefinition
      DesiredCount: !Ref DesiredCount
      LaunchType: "FARGATE"
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          Subnets:
            - !Ref Subnet1
            - !Ref Subnet2
          SecurityGroups:
            - !Ref SecurityGroup
      ServiceConnectConfiguration:
        Enabled: true
        Namespace: !Sub "${ServiceName}-namespace"
        Services:
          - PortName: "http"
            DnsName: !Sub "${ServiceName}-${ServiceVersion}"
            Port: 80
            ClientAliases:
              - DnsName: !Sub "${ServiceName}-${ServiceVersion}.svc.local"

Outputs:
  ECSServiceDNS:
    Description: "The DNS name of the ECS service in Service Connect"
    Value: !Sub "${ServiceName}-${ServiceVersion}.svc.local"
