openapi: 3.0.0
info:
  title: MyService API
  version: 1.0.0
servers:
  - url: http://localhost:8080
  - url: http://localhost:8090

paths:
  /v1/getuser:
    get:
      summary: Get User Information
      operationId: getUser
      parameters:
        - name: user_id
          in: query
          required: true
          schema:
            type: string
          description: The ID of the user
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetUserResponse'
        '400':
          description: Invalid user ID supplied
        '404':
          description: User not found

components:
  schemas:
    GetUserResponse:
      type: object
      properties:
        name:
          type: string
          description: The user's name
        age:
          type: integer
          description: The user's age
